overblog_graphql:
    definitions:
        schema:
            query: RootQuery
            mutation: RootMutation
        mappings:
            types:
                -   type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
                -   type: annotation
                    dir: "%kernel.project_dir%/src/GraphQL"
                    suffix: ~
        use_classloader_listener: false
        auto_compile: true
        cache_dir: "%kernel.project_dir%/var/cache/graphql_types"
